[package]
name = "yjk_selector"
version = "2.0.0"
authors = ["Junjie <git@junjie.im>"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
